projects:
  app:
    schemaPath: ./gql/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: ./gql/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml