version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://api-dev:development123@keybot-dev-shard-00-00-2zead.mongodb.net:27017,keybot-dev-shard-00-01-2zead.mongodb.net:27017,keybot-dev-shard-00-02-2zead.mongodb.net:27017/test?ssl=true&replicaSet=Keybot-Dev-shard-0&authSource=admin&retryWrites=true